exxcellent/swt2-bsa-backend

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/competitionclass/mapper/CompetitionClassDTOMapper.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/competitionclass/model/CompetitionClassDTO.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/competitionclass/service/CompetitionClassService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/competitionclass/service/CompetitionClassServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/api/types/CompetitionClassDO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/business/CompetitionClassComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/dao/CompetitionClassDAO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/entity/CompetitionClassBE.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/mapper/CompetitionClassMapper.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionClass/impl/business/CompetitionClassComponentImplTest.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionclass/impl/dao/CompetitionClassDAOTest.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionclass/impl/entity/CompetitionClassBETest.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionclass/impl/mapper/CompetitionClassMapperTest.java, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V30__klasse__insert_dsb_klassen.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/all/V7__klasse__create.sql
Changed naming of 2 table columns because they were not named as intended.
=> Changed naming of 2 table columns

bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V35__veranstaltung__insert_ligen.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/PROD-DATA-MIGRATION/V1016__insert_veranstaltung.sql
Fixes für die Insert-Sktipten der Entität Veranstaltung sowohl in den Testdaten als auch in der Prod-Migration
=> Db fix veranstaltung

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/regionen/mapper/RegionenDTOMapper.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/regionen/model/RegionenDTO.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/regionen/service/RegionenService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/regionen/service/RegionenServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/regionen/api/RegionenComponent.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/regionen/api/types/RegionenDO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/regionen/impl/business/RegionenComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/regionen/impl/dao/RegionenDAO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/api/VereinComponent.java
BSAPP251: RegionenDTO Objekt bearbeitet. D.h. von den Attributen teilweise den Namen geändert. Im RegionenService die passenden Methoden zum Anlegen, Bearbeiten und Löschen einer Region hinzugefügt. Die dafür notwendigen Methoden in den darunterliegenden Mapper, Service und Objekt Komponenten hinzugefügt.
=> Srummasters of desaster

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/match/service/MatchService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/veranstaltung/service/VeranstaltungService.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/passe/impl/business/PasseComponentImpl.java
Bugfixes und kleine Erweiterungen rund um die Schusszetteleingabe
=> Bsapp 453 liga tabelle anzeigen

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/user/service/UserService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/user/service/UserServiceTest.java
Added Password Validity-Check on the server-side (as well as on the client-side). The server won't accept new users with passwords, that don't match the specified pattern.
Created tests for the regular expression.
=> Fixed Issue BSAPP-488

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/competitionclass/service/CompetitionClassService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/user/service/UserService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/competitionclass/service/CompetitionClassServiceTest.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/user/service/UserServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/business/CompetitionClassComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/competitionclass/impl/mapper/CompetitionClassMapper.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionclass/impl/business/CompetitionClassComponentImplTest.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/competitionclass/impl/mapper/CompetitionClassMapperTest.java
Implemented a mechanism, that automatically sets the higher year as the min year and the lower year as the max year of a competition class.
Updated Tests accordingly.
Fixed an issue in the business logic when only having one year as min and max.
Refactored duplicate code in this class and extracted it into two methods.
=> Fixed Issue BSAPP-489

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/Schusszettel/impl/business/SchusszettelComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/impl/business/VereinComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/vereine/impl/business/VereinComponentImplTest.java
Bug : BSAPP-512
Code Änderung 
Die Regionen werden richtig angezeigt .
=> Ligaleiter ws19

bogenliga/bogenliga-application/src/main/resources/db/migration/LOCAL/V67__benutzer_rolle__update.sql, bogenliga/bogenliga-application/src/main/resources/db/migration/PROD/V66__rolle_recht__update.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V67__benutzer_rolle__update.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/PROD/V66__rolle_recht__update.sql
Added SQL Scripts for production
=> Bugfix Roles

bogenliga/bogenliga-application/src/main/resources/db/migration/all/V300__wettkampftag__0__create.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/all/V300__wettkampftag__0__create.sql
Script zur automatischen Erzeugung des Wettkampftag 0 für schon existierende Veranstaltungen
=> Script zur automatischen Erzeugung des Wettkampftag 0

bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V68__liga__uebergeordnete__update.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/PROD/V69__liga__uebergeordnete__update.sql
Added 2 Scriptes that update undifined liga_uebergeordnete
=> Fixed Bug BSAPP-493. 

bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V58__benutzer_rolle__insert_test_data.sql, bogenliga/bogenliga-db-migration/src/main/resources/db/migration/LOCAL/V70__benutzer_rolle_insert_test_data_update.sql
Rollenzuweisung des Test-Standard-Benutzers war falsch eingetragen und wurde verbessert.
=> Trage korrekte Rollenzuweisung ein.

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/match/impl/dao/MatchDAO.java
~ MatchDAO.java: changed the order the values get read out of the database. First search of Matchpunkte are null then sort by MatchNr, Scheibennummer.
=> Changed the Order the Values in "Ligatabelle Durchführung"

bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/mannschaftsmitglied/impl/MannschaftsmitgliedBaseDAOTest.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/mannschaftsmitglied/impl/entity/MannschaftsmitgliedBETest.java
+ added column for rueckennummer in table mannschaftsmitglied
+ added alterscript
~ changed all layers that it's possible to work with rueckennummer and add one
~ fixed tests
=> Felix und Maxi haben Rückennummern eingefuehrt und Tabellen/Tests dazu angepasst

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/schusszettel/impl/business/SchusszettelComponentImpl.java
Reihenfolge der Passen anpassen, sodass es sich richtig and der lfdnr orientiert.
=> BSAPP-619 fertigstellen

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/springconfiguration/security/types/UserPermission.java, bogenliga/bogenliga-application/src/main/resources/db/migration/PROD/V304_AdminCRRECHT.sql, bogenliga/bogenliga-application/src/main/resources/db/migration/all/V302_createRECHT.sql
Verschiebung der SQL Dateien damit diese auf der Prod laufen
=> fixed Create permissions

bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/user/service/UserServiceTest.java
+Tests für die eingefügten Daten ins UserSignInDTO
=> + Tests for new values added to UserService login method

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/veranstaltung/service/VeranstaltungService.java
die Permission wurde von can_modify_my_veranstaltung zu can_modify_stammdaten reverted
=> ~ wrong permission in VeranstaltungService update() changed

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/vereine/service/VereineService.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/api/VereinComponent.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/impl/business/VereinComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/impl/dao/VereinDAO.java
Habe den findFirst wieder entfernt und andere Überbleibsel Auskomentierten Code entfernt.
Achtung! es gibt hierzu auch einen request im Frontend
=> Aufräumen von nicht mehr benötigten funktionen.

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/BogenligaApplication.java, bogenliga/bogenliga-application/src/main/resources/db/migration/LOCAL/V2_klasse_alter.sql, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/schusszettel/impl/business/SchusszettelComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/veranstaltung/impl/business/VeranstaltungComponentImpl.java
=> Gruppenbranch_GhostCoder

bogenliga/bogenliga-application/src/main/resources/db/migration/DEV/V1011__check_admin_permission_create_data_DEV.sql, bogenliga/bogenliga-application/src/main/resources/db/migration/LOCAL/README.md, bogenliga/bogenliga-application/src/main/resources/db/migration/LOCAL/V1011__check_admin_permission_create_data_LOCAL.sql, bogenliga/bogenliga-application/src/main/resources/db/migration/PROD/V1011__check_admin_permission_create_data_PROD.sql, package-lock.json
=> Solutionlounge

bogenliga/bogenliga-common/src/main/java/de/bogenliga/application/common/database/tx/SessionHandler.java
Added the remove() call on THREAD_LOCAL in the remove()-method.
=> Call "remove()" on "THREAD_LOCAL".

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/competitionclass/service/CompetitionClassService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/configuration/service/ConfigurationService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/download/DownloadService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/dsbmannschaft/service/MannschaftSortierungService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/dsbmitglied/service/DsbMitgliedService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/einstellungen/service/EinstellungenService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/errortesting/ErrorTestingService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/feedback/service/FeedbackClassService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/kampfrichter/service/KampfrichterService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/liga/service/LigaService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/ligatabelle/service/LigatabelleService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/lizenz/service/LizenzService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/mannschaftsmitglied/service/MannschaftsMitgliedService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/match/service/MatchService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/passe/service/PasseService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/regionen/service/RegionenService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/role/service/RoleService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/setzliste/service/SetzlisteService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/tabletsession/service/TabletSessionService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/user/service/UserService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/veranstaltung/service/VeranstaltungService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/vereine/service/VereineService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/wettkampf/service/WettkampfService.java, bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/wettkampftyp/service/WettkampfTypService.java
Replaced RequestMapping(method = RequestMethod.GET) with GetMapping and so on
=> Replaced RequestMapping BSAPP-848

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/sportjahr/mapper/SportjahrDTOMapper.java
=> Added private Constructor to SportjahrDTOMapper

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/rueckennummern/impl/business/RueckennummernComponentImpl.java
=> weiterer  mini fix

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/dsbmannschaft/service/DsbMannschaftService.java
Changed == to equals in DsbMannschaftsService.java
=> Changed == to equals

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/sportjahr/model/SportjahrDTO.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/sportjahr/model/SportjahrDTOTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/sportjahr/api/types/SportjahrDO.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/sportjahr/api/types/SportjahrDOTest.java
-Added Tests to SportjahrDO and SportjahrDTO
-Added class documentation.
-Removed unnecessary import in SportjahrDO.
-Added @Override annotation at the necessary methods in SportjahrDO.
=> -Added Tests to SportjahrDO and SportjahrDTO

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/schusszettel/impl/business/SchusszettelComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/schusszettel/impl/business/SchusszettelComponentImplTest.java
=> change .size()==0 into isEmpty()

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImplTest.java
Constant instead of duplicated literal, removed unused imports, replaced lambda with method reference, renamed some variables
=> BSAPP-852 Code Smells in DsbMannschaftComponentImpl.java

bogenliga/bogenliga-common/src/test/java/de/bogenliga/application/common/configuration/DatabaseConfigurationTest.java
use isZero instead of isEqualTo(0)
=> use isZero instead of isEqualTo(0)

bogenliga/bogenliga-common/src/main/java/de/bogenliga/application/common/database/migration/DBMigrationLogger.java
commented out line that was previously commented out to prevent possible issues with it
=> commented out line again to prevent issues

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/feedback/mapper/FeedbackClassDTOMapper.java
=> made interface of class

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/dsbmannschaft/service/DsbMannschaftService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/dsbmannschaft/service/DsbMannschaftServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/dsbmannschaft/api/DsbMannschaftComponent.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImplTest.java
Ermöglicht das Kopieren von alten Mannschaften auf der Veranstaltungsseite
=> Merge Bsapp 764-4

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/user/impl/businessactivity/SignInBA.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/user/impl/businessactivity/SignInBATest.java
Die Benachrichtigung für zu viele fehlgeschlagene Anmeldeversuche soll nach dem fünften Versuch auftauchen. Die Benachrichtigung soll noch richtig geschrieben werden.
=> Pull Request - BSAPP 817

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/user/impl/businessactivity/SignInBA.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/user/impl/businessactivity/SignInBATest.java
Test in SignInBATest (Z. 116), welcher im letzten Push fehlerhaft war und auskommentiert wurde, wird gefixed
=> Push Korrektur Bsapp 817

bogenliga/bogenliga-application/src/main/resources/db/migration/LOCAL/V26_0__update_veranstaltung.sql
deleted duplicated sql statements
=> Bsapp 683/686 deleted duplicates

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImpl.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/vereine/api/types/VereinDO.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/dsbmannschaft/impl/business/DsbMannschaftComponentImplTest.java
Architektur Umbau von dsbmannschaft.
=> T2D Architektur-verletzung

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/download/DownloadService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/download/DownloadServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/ligatabelle/impl/dao/LigatabelleDAO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/wettkampf/api/WettkampfComponent.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/wettkampf/impl/business/WettkampfComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/wettkampf/impl/business/WettkampfComponentImplTest.java
Reverts exxcellent/swt2-bsa-backend#329
=> Revert "Groupbranch forgottensemicolon"

bogenliga/bogenliga-application/src/main/java/de/bogenliga/application/services/v1/download/DownloadService.java, bogenliga/bogenliga-application/src/test/java/de/bogenliga/application/services/v1/download/DownloadServiceTest.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/ligatabelle/impl/dao/LigatabelleDAO.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/wettkampf/api/WettkampfComponent.java, bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/wettkampf/impl/business/WettkampfComponentImpl.java, bogenliga/bogenliga-business-logic/src/test/java/de/bogenliga/application/business/wettkampf/impl/business/WettkampfComponentImplTest.java
=> Groupbranch forgottensemicolon

bogenliga/bogenliga-business-logic/src/main/java/de/bogenliga/application/business/regionen/impl/business/RegionenComponentImpl.java
Cleaned the logger to switch from string concatenation to formatting. 
https://www.exxcellent.de/jira/browse/BSAPP-1015
=> Cleaned logger
